import type { ManagerContactMatch } from "./types";

function escapeHtml(value: string) {
  return value.replace(/[&<>'"]/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character] ?? character);
}

function markdownLink(label: string, url: string) {
  return `[${label.replace(/[\[\]]/g, "")}](${url})`;
}

export type ManagerChecklistInput = {
  requestId: number;
  source: "onesite" | "yardi";
  reportName: string;
  reportStatus: string;
  generatedAt: Date;
  property: { name: string; externalId: string; market?: string | null; managerName?: string | null; managerEmail?: string | null };
  summaryMarkdown?: string | null;
  warningSummary?: string | null;
  documents: Array<{ originalFilename: string; storageUrl: string }>;
  contacts?: ManagerContactMatch;
};

export function buildManagerChecklist(input: ManagerChecklistInput) {
  const sourceName = input.source === "onesite" ? "OneSite" : "Yardi";
  const firstContact = input.contacts?.propertyContacts.find(contact => contact.managerName || contact.email);
  const manager = firstContact?.managerName || input.property.managerName || "Property manager";
  const managerEmail = firstContact?.email || input.property.managerEmail || null;
  const opening = `This checklist was prepared from the ${sourceName} report “${input.reportName}” for ${input.property.name}. Review the source report alongside the items below before finalizing action items.`;
  const findings = input.summaryMarkdown?.trim() || "The runner did not provide a narrative summary. Review the original filed report for report-specific detail.";
  const warning = input.warningSummary?.trim();
  const contactLines = input.contacts?.propertyContacts.length
    ? input.contacts.propertyContacts.map(contact => `- ${contact.managerName ?? "Unnamed contact"}${contact.email ? ` — ${contact.email}` : ""}${contact.region ? ` (${contact.region})` : ""}`).join("\n")
    : `- ${manager}${managerEmail ? ` — ${managerEmail}` : ""}`;
  const regionalLines = input.contacts?.regionalContacts.length
    ? input.contacts.regionalContacts.map(contact => `- ${contact.managerName ?? "Regional manager"}${contact.email ? ` — ${contact.email}` : ""}${contact.region ? ` (${contact.region})` : ""}`).join("\n")
    : "- No regional manager match has been synchronized for this property yet.";
  const documents = input.documents.length ? input.documents.map(document => `- ${markdownLink(document.originalFilename, document.storageUrl)}`).join("\n") : "- No original document has been filed yet.";
  const markdown = `# Manager’s Checklist — ${input.property.name}\n\n**Report:** ${input.reportName}  \n**Source:** ${sourceName}  \n**Request:** #${input.requestId}  \n**Status:** ${input.reportStatus.replaceAll("_", " ")}  \n**Prepared:** ${input.generatedAt.toLocaleString()}  \n**Manager:** ${manager}${managerEmail ? ` (${managerEmail})` : ""}\n\n## Purpose\n${opening}\n\n## Matched contacts\n${contactLines}\n\n## Regional support\n${regionalLines}\n\n## Report overview\n${findings}\n${warning ? `\n## Runner note\n${warning}\n` : ""}\n## Discussion checklist\n- [ ] Confirm the report period and property scope are correct.\n- [ ] Review each material finding in the original report.\n- [ ] Identify manager-owned actions, owners, and target dates.\n- [ ] Record blockers or decisions requiring regional support.\n- [ ] Confirm follow-up timing and the next review date.\n\n## Original filed reports\n${documents}\n\n---\nGenerated by OneSite Reporting Hub. This checklist supplements, but does not replace, the original source report.`;
  const htmlDocumentLinks = input.documents.length ? input.documents.map(document => `<li><a href="${escapeHtml(document.storageUrl)}" target="_blank" rel="noreferrer">${escapeHtml(document.originalFilename)}</a></li>`).join("") : "<li>No original document has been filed yet.</li>";
  const htmlContactLines = input.contacts?.propertyContacts.length ? input.contacts.propertyContacts.map(contact => `<li>${escapeHtml(contact.managerName ?? "Unnamed contact")}${contact.email ? ` — <a href="mailto:${escapeHtml(contact.email)}">${escapeHtml(contact.email)}</a>` : ""}${contact.region ? ` (${escapeHtml(contact.region)})` : ""}</li>`).join("") : `<li>${escapeHtml(manager)}${managerEmail ? ` — <a href="mailto:${escapeHtml(managerEmail)}">${escapeHtml(managerEmail)}</a>` : ""}</li>`;
  const htmlRegionalLines = input.contacts?.regionalContacts.length ? input.contacts.regionalContacts.map(contact => `<li>${escapeHtml(contact.managerName ?? "Regional manager")}${contact.email ? ` — <a href="mailto:${escapeHtml(contact.email)}">${escapeHtml(contact.email)}</a>` : ""}${contact.region ? ` (${escapeHtml(contact.region)})` : ""}</li>`).join("") : "<li>No regional manager match has been synchronized for this property yet.</li>";
  const html = `<!doctype html><html><head><meta charset="utf-8" /><title>Manager’s Checklist — ${escapeHtml(input.property.name)}</title></head><body style="margin:0;background:#f4f6fb;color:#17233b;font-family:Inter,Arial,sans-serif"><main style="max-width:860px;margin:0 auto;padding:40px 24px"><header style="background:#0c1d35;border-radius:24px;padding:32px;color:white"><p style="margin:0 0 8px;font-size:11px;letter-spacing:.14em;text-transform:uppercase;color:#8de1d1">${sourceName} Reporting · Manager Follow-up</p><h1 style="margin:0;font-size:30px">${escapeHtml(input.property.name)}</h1><p style="margin:12px 0 0;color:#c9d5e8;font-size:14px">${escapeHtml(input.reportName)} · Request #${input.requestId}</p></header><section style="display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-top:18px"><div style="background:white;border-radius:16px;padding:16px"><small style="color:#64748b;text-transform:uppercase;letter-spacing:.1em">Manager</small><p style="margin:7px 0 0;font-weight:700">${escapeHtml(manager)}</p>${managerEmail ? `<p style="margin:4px 0 0;color:#64748b;font-size:12px">${escapeHtml(managerEmail)}</p>` : ""}</div><div style="background:white;border-radius:16px;padding:16px"><small style="color:#64748b;text-transform:uppercase;letter-spacing:.1em">Status</small><p style="margin:7px 0 0;font-weight:700">${escapeHtml(input.reportStatus.replaceAll("_", " "))}</p></div><div style="background:white;border-radius:16px;padding:16px"><small style="color:#64748b;text-transform:uppercase;letter-spacing:.1em">Prepared</small><p style="margin:7px 0 0;font-weight:700">${escapeHtml(input.generatedAt.toLocaleString())}</p></div></section><section style="margin-top:18px;background:white;border-radius:20px;padding:28px;line-height:1.7"><h2 style="margin-top:0">Purpose</h2><p>${escapeHtml(opening)}</p><h2>Matched contacts</h2><ul style="padding-left:20px">${htmlContactLines}</ul><h2>Regional support</h2><ul style="padding-left:20px">${htmlRegionalLines}</ul><h2>Report overview</h2><p style="white-space:pre-wrap">${escapeHtml(findings)}</p>${warning ? `<aside style="border-left:4px solid #b45309;background:#fffaf0;padding:14px 16px;border-radius:8px"><strong>Runner note</strong><br />${escapeHtml(warning)}</aside>` : ""}<h2>Discussion checklist</h2><ul style="padding-left:20px"><li>Confirm the report period and property scope are correct.</li><li>Review each material finding in the original report.</li><li>Identify manager-owned actions, owners, and target dates.</li><li>Record blockers or decisions requiring regional support.</li><li>Confirm follow-up timing and the next review date.</li></ul><h2>Original filed reports</h2><ul style="padding-left:20px">${htmlDocumentLinks}</ul></section><footer style="padding:22px 4px;color:#64748b;font-size:12px">Generated by OneSite Reporting Hub. This checklist supplements, but does not replace, the original source report.</footer></main></body></html>`;
  return { markdown, html, contacts: input.contacts ?? { propertyContacts: [], regionalContacts: [], matchedRegion: null } };
}
