function escapeHtml(value: string) {
  return value.replace(/[&<>'"]/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character] ?? character);
}

function paragraphHtml(value: string) {
  return value.split(/\n{2,}/).filter(Boolean).map(paragraph => `<p>${escapeHtml(paragraph).replace(/\n/g, "<br />")}</p>`).join("");
}

export function renderReportSummaryHtml(input: { source: "onesite" | "yardi"; reportName: string; status: string; requestId: number; completedAt: Date; summaryMarkdown?: string | null; warningSummary?: string | null; errorMessage?: string | null }) {
  const sourceName = input.source === "onesite" ? "OneSite" : "Yardi";
  const primary = input.summaryMarkdown?.trim() || (input.status === "failed" ? "The runner reported a failure before the report could be completed." : "The runner completed the report and filed its source documents.");
  const detailBlock = input.status === "failed" ? input.errorMessage : input.warningSummary;
  const tone = input.status === "failed" ? "#be123c" : input.warningSummary ? "#b45309" : "#087365";
  return `<!doctype html><html><head><meta charset="utf-8" /><title>${escapeHtml(input.reportName)} — Report Summary</title></head><body style="margin:0;background:#f4f6fb;color:#16233b;font-family:Inter,Arial,sans-serif"><main style="max-width:860px;margin:0 auto;padding:40px 24px"><section style="background:#0c1d35;border-radius:24px;padding:32px;color:white"><p style="margin:0 0 8px;font-size:11px;letter-spacing:.14em;text-transform:uppercase;color:#8de1d1">${sourceName} Reporting</p><h1 style="margin:0;font-size:30px;line-height:1.2">${escapeHtml(input.reportName)}</h1><p style="margin:12px 0 0;color:#c9d5e8;font-size:14px">Filed report summary · Request #${input.requestId}</p></section><section style="display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-top:18px"><div style="background:white;border-radius:16px;padding:16px"><p style="margin:0;color:#64748b;font-size:11px;text-transform:uppercase;letter-spacing:.1em">Source</p><p style="margin:7px 0 0;font-weight:700">${sourceName}</p></div><div style="background:white;border-radius:16px;padding:16px"><p style="margin:0;color:#64748b;font-size:11px;text-transform:uppercase;letter-spacing:.1em">Status</p><p style="margin:7px 0 0;font-weight:700;color:${tone}">${escapeHtml(input.status.replaceAll("_", " "))}</p></div><div style="background:white;border-radius:16px;padding:16px"><p style="margin:0;color:#64748b;font-size:11px;text-transform:uppercase;letter-spacing:.1em">Generated</p><p style="margin:7px 0 0;font-weight:700">${escapeHtml(input.completedAt.toLocaleString())}</p></div></section><section style="margin-top:18px;background:white;border-radius:20px;padding:28px;line-height:1.7"><h2 style="margin:0 0 14px;font-size:18px">Report overview</h2>${paragraphHtml(primary)}${detailBlock ? `<aside style="margin-top:18px;border-left:4px solid ${tone};background:#fffaf0;padding:14px 16px;border-radius:8px"><strong>${input.status === "failed" ? "Runner failure" : "Runner note"}</strong><br />${escapeHtml(detailBlock)}</aside>` : ""}</section><footer style="padding:22px 4px;color:#64748b;font-size:12px">This summary accompanies the preserved original report output. Review the original PDF or workbook for source detail.</footer></main></body></html>`;
}
